# -*- mode:yaml; indent-tabs-mode: nil; -*-
---
name: CI

on:
  push:
    branches:
      - 'main'
      - 'g*'
  pull_request:
    branches:
      - 'main'
      - 'g*'

jobs:
  php_test_matrix:
    uses: ./.github/workflows/build-and-test.yml
    with:
      php-version: ${{  matrix.php-version }}"
      compiler-optimization-level: '2'
      valgrind-tool: 'none'
