# -*- mode:yaml; indent-tabs-mode: nil; -*-
---
name: CI

on:
  push:
    branches:
      - 'main'
      - 'g*'
  pull_request:
    branches:
      - 'main'
      - 'g*'

jobs:
  php_test_matrix:
    name: Test in PHP version
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "7.4"
          - "8.1"

    uses: ./.github/workflows/build-and-test.yml
    with:
      php-version: ${{  matrix.php-version }}"
      compiler-optimization-level: '2'
      valgrind-tool: 'none'
